i = input()
first = int(i)
second = input()
second_1 = int(second[2])
second_2 = int(second[1])
second_3 = int(second[0])

print(first * second_1)
print(first * second_2)
print(first * second_3)
print(first * second_1 + first * second_2 * 10 + first * second_3 * 100)