enter = input()
enter = enter.replace('lj', '_')
enter = enter.replace('nj', '_')
enter = enter.replace('dz=', '_')
enter = enter.replace('c=', '_')
enter = enter.replace('s=', '_')
enter = enter.replace('z=', '_')
enter = enter.replace('c-', '_')
enter = enter.replace('d-', '_')
print(len(enter))
